//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace customer_supports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class custinfo
    {
        public int logid { get; set; }
        public string customer_email { get; set; }
        public string customer_name { get; set; }
        public string log_status { get; set; }
        public string descriptions { get; set; }
    }
}
